apply plugin: 'digital.wup.android-maven-publish'

task sourcesJar(type: Jar) {
    from sourceSets.main.java.srcDirs
    classifier = 'sources'
    version = VERSION
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    classifier = 'javadoc'
    from javadoc.destinationDir
    version = VERSION
}

publishing {
    repositories {
        maven {
            url System.getenv("MAVEN_URL")
            credentials {
                username System.getenv("MAVEN_UPLOAD_USER")
                password System.getenv("MAVEN_UPLOAD_PASS")
            }
            allowInsecureProtocol true
        }
    }

    publications {
        Plugin(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact javadocJar

            groupId GROUP_ID
            artifactId ARTIFACT_ID
            version VERSION
        }
    }
}