apply plugin: 'java-library'
apply plugin: 'kotlin'
apply plugin: "groovy"
apply from: rootProject.file('gradle/publish_plugin.gradle')

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation gradleApi()
    implementation localGroovy()
    compileOnly "com.android.tools.build:gradle:7.3.0"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.0.21"
    implementation "org.jetbrains.kotlin:kotlin-gradle-plugin:2.0.21"
    compileOnly "$GROUP_ID:aabresguard-core:$VERSION"
    api("$GROUP_ID:aabresguard-core:$VERSION") {
        exclude group: "com.google.guava", module: "guava"
        exclude group: "com.android.tools.build", module: "gradle"
    }
}

configurations {
    all*.exclude group: "com.android.tools.build", module: "bundletool"
}

sourceCompatibility = 11
targetCompatibility = 11
